### ISSUE TITLE
Make distinction between root finding algorithm and function clearer

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/cpp2wasm#29]
At the moment the `x^3 - x^2 + 2` function and its derivative are hard to distinguish from the root finding algorithm. It would be nice if the function + derivative could be moved to their own code block
So it is clearer we are trying to find the root of the  `x^3 - x^2 + 2` function with the Newton-Raphson algorithm.

**Comment by sverhoeven** [comment]
And rename `func` to `equation` and `derivFunc` to `derivative`.

**Comment by fdiblen** [comment]
also rename `find` to `solve`.
