### ISSUE TITLE
Add plot of function

### ISSUE THREAD

**Issue by sverhoeven** [NLESC-JCER/cpp2wasm#30]
As graphically oriented person it would help me if the function we are trying to find a root for can be plotted. That way I can better understand why the answer is `-1`.

For example embed something like https://www.desmos.com/calculator/yj0ih4ml0i

**Comment by sverhoeven** [comment]
We can use [docsify embedding](https://docsify.js.org/#/embed-files?id=embed-files) to embed the interactive plot for example with

```markdown
[Plotted](https://www.desmos.com/calculator/hfb3rvqouv?embed ':include :type=iframe')
```

**Comment by fdiblen** [comment]
Is generating the plot using some JavaScript library an option or we really want to use an external service?

**Comment by sverhoeven** [comment]
No using a svg would also be fine.
