### ISSUE TITLE
notes on CONTRIBUTING

### ISSUE THREAD

**Issue by jspaaks** [NLESC-JCER/cpp2wasm#62]
I've collected some remarks about CONTRIBUTING.md. They are numbered so we can more easily discuss / decide / spawn new issues if necessary.

1. [CONTRIBUTING.md#L24-L32](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L24-L32) might be covered by the bug template, maybe remove from CONTRIBUTING or just point to [the bug template](https://github.com/NLESC-JCER/cpp2wasm/issues/new?assignees=&labels=bug&template=10_bug_report.md&title=)

1. [CONTRIBUTING.md#L48-L53](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L48-L53) We could update the _New feature_ issue template and remove the text here

1. [CONTRIBUTING.md#L63](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L63) I prefer the https link

1. [CONTRIBUTING.md#L104](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L104) this raises the threshold for making contributions. Maybe add something like "_It's good practice to add tests when adding new functionality or changing existing functionality_"

1. [CONTRIBUTING.md#L100-L111](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L100-L111) We could move this whole part to a PR template file, that way people at least get to see it. I myself hardly ever follow the _Check the CONTRIBUTING_ link that GitHub provides when making PRs.

1. I believe this [CONTRIBUTING.md#L117-L121](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L117-L121) was just updated, we should update accordingly. 

1. We could wrap [CONTRIBUTING.md#L120](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L120) in a script, e.g. ``dockerized-entangled``. Perhaps we can even pass its arguments to inside the docker container. Or we could update the instructions to use ``make entangle`` instead.

1. I would prefer to not have the git hook [CONTRIBUTING.md#L136-L179](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L136-L179), I find it surprising. As an alternative, maybe we can run the same functionality as a GitHub action; that way you get the check on code being in sync without surprising the user.

Let me know which of these suggestions you find useful, we can take it from there.

**Comment by sverhoeven** [comment]
I think note 1,2,3,4,5 are good suggestions and can be wrapped up in a single PR.

For 6, pandoc-tangle is still the preferred way to tangle. When entangled is made the preferred way in  PR #53 then CONTRIBUTING.md should be updated accordingly.

For 7, `make entangle` is documented at [L81](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L81), for literate programming we need someplace to have the Docker command. The best I can think of is to have in the [tip1 chapter](https://github.com/NLESC-JCER/cpp2wasm/blame/e905743f756156ffebfd946a83bcfa888c013580/CONTRIBUTING.md#L115) the docker command and give the make command as an alternative underneath.

For 8, The githook is optional so you can ignore it if you want to. In [GH CI job](https://github.com/NLESC-JCER/cpp2wasm/blob/master/.github/workflows/main.yml#L16) we already check if everything is in sync. Performing commits in a GitHub action is a surprise to me. So perhaps making it clearer that the githook is optional would help you?

**Comment by sverhoeven** [comment]
Most points raised have been fixed in #97, can this issue be closed?

**Comment by jspaaks** [comment]
> can this issue be closed

good with me
