### ISSUE TITLE
Update pre-commit hook

### ISSUE THREAD

**Issue by fdiblen** [NLESC-JCER/cpp2wasm#64]
`UID` variable in .githooks/pre-commit is a readonly variable on my system.

Renaming this variable ill solve the issue.
Related Stackoverflow thread: https://stackoverflow.com/questions/13404665/use-of-read-only-variables-in-shell-scripts

Linux Distro:  Arch Linux 
Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by jspaaks** [comment]
Or use the expression without assignment to a variable, e.g. like here https://github.com/entangled/entangled/blame/d1bce3932d9ced4e40f104bd723f42e32890af12/README.md#L113

Not sure if we should also add the user's group, I'm guessing yes.

**Comment by jspaaks** [comment]
PR #https://github.com/NLESC-JCER/cpp2wasm/pull/68

**Comment by sverhoeven** [comment]
We could also use https://pre-commit.com/ as a wrapper for a docker command.

**Comment by fdiblen** [comment]
fixed by #68
