### ISSUE TITLE
JavaScript web service using Emscripten and WebAssembly

### ISSUE THREAD

**Issue by fdiblen** [NLESC-JCER/cpp2wasm#83]
We would like to reorganize the guide and have several chapters. 
See the link below for the outline (README.outline.md):
https://github.com/NLESC-JCER/cpp2wasm/pull/71/files#diff-20b48d680d0cbd36f087c68e1a55b61d

In this chapter, we will talk about emscripten, how we generate WebAssembly code and how we use it.

**Comment by sverhoeven** [comment]
Use [expressjs](http://expressjs.com/) as framework.

To install and run do

```shell
npm install expressjs
node expressjs/service.js
```

Content expressjs/service.js
```
const express = require('express')
const app = express()
const port = 3000

// TODO root find function hosted at /

app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))
```

Test with curl

**Comment by sverhoeven** [comment]
Decided to use [Fastify](https://www.fastify.io/) as web framework as it supports async/await and JSON schemas.
